language: python
python:
  - "3.3"
  - "3.4"
branches:
  only:
    - master
    - develop
notifications:
  email: false

sudo: false

addons:
  apt:
    sources:
      debian-sid
    packages:
      qt-default

before_install:
  - bash continuous-integration/travis/install.sh

install:
  - export PATH="$HOME/cachedir/miniconda/bin:$PATH"
  - source activate test-environment
  - which python
  - conda list
  - python setup.py install

before_script:
  - ls $HOME
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

# Run test
script:
  - py.test -v --cov corpustools tests/

# Calculate coverage
after_success:
  - coveralls

cache:
  directories:
    - $HOME/cachedir
  apt: true
